# Atom-level knowledge graph

This notebook builds and explores the atom-level knowledge graph for the WGBO
corpus and its Book 6 fallbacks. Each Dutch Civil Code article is decomposed
into atoms defined as the smallest units carrying a single legal meaning, annotated
against a 9-label schema, and connected into a graph through four edge
channels: shared annotation tags (IDF-weighted), semantic similarity between
tag values, hierarchical containment through the Dutch legal tree, and
explicit cross-article references.

On top of that graph, a classifier ranks atoms against a query, and a
chained-reasoning walker expands from the top matches through the graph so
every result names the edge that surfaced it.

Section flow:

1. Load the atom table
2. Corpus overview
3. Cross-article edges
4. Article-level connectivity
5. Tag weighting (IDF)
6. Semantic similarity
7. Atom classifier and evaluation
8. Legal hierarchy : placing atoms in the Dutch civil code tree
9. Chained reasoning demo : walking the graph from a query

Model comparison and alpha/top-k sweeps live in `02_experiments.ipynb`.

## 1. Load the atom table

In [1]:
import sys
import os
from pathlib import Path


def find_project_root(marker='src/data/atom_table.py'):
    for p in [Path.cwd().resolve(), *Path.cwd().resolve().parents]:
        if (p / marker).exists():
            return p
    raise RuntimeError(f"Could not find project root (no {marker} in any parent)")


PROJECT_ROOT = find_project_root()
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))
os.chdir(PROJECT_ROOT)

import pandas as pd
pd.set_option('display.max_colwidth', 70)
pd.set_option('display.width', 220)

from src.data.atom_table import (
    build_atom_table, summary_stats, tag_frequencies, show_atom,
    build_edge_table, add_edge_summary, article_connectivity,
    compute_tag_weights, show_tag_weights,
    compute_tag_similarities, build_semantic_edge_table, unique_tags_by_field,
    classify_atom, evaluate_classifier_loo, evaluate_article_retrieval, drop_synthetic,
    LIST_FIELDS,
)

df = build_atom_table()
print(f'Loaded {len(df)} atoms across {df["article_id"].nunique()} articles')
df.head()

Loaded 118 atoms across 45 articles

,atom_id,article_id,lid,condition_type,text,text_nl,actors,legal_relations,acts,geographical_domain,temporal,explicit_references,hierarchies,residual,source,annotator,annotated_at,notes
0,6:101(1).a,6:101,1,post_condition,When damage is also a consequence of a circumstance that can be at...,Wanneer de schade mede een gevolg is van een omstandigheid die aan...,"[injured party, party obliged to compensate]",[],"[reduces, divides]",[],[],[],[],"[damage, circumstance, attribution, proportion, contribution]","Dutch Civil Code, Book 6, Title 6.1.10",Claude-draft,13/09/2026,Proportional-reduction rule for contributory fault. Central defens...
1,6:101(1).b,6:101,1,pre_condition,"with the understanding that a different division takes place, or t...",met dien verstande dat een andere verdeling plaatsvindt of de verg...,"[injured party, party obliged to compensate]",[],[],[],[],[],[],"[division, obligation, equity, severity, mistakes, circumstances]","Dutch Civil Code, Book 6, Title 6.1.10",Claude-draft,13/09/2026,Equity override on (1).a's proportional division — allows courts t...
2,6:101(2).a,6:101,2,post_condition,If for the damage there also exists a ground for liability of a th...,Indien voor de schade tevens een grond voor aansprakelijkheid van ...,"[injured party, third party]",[],[],[],[],[paragraph 1],[],"[damage, liability, ground, mutatis mutandis]","Dutch Civil Code, Book 6, Title 6.1.10",Claude-draft,13/09/2026,Extends contributory fault to third-party defendants (e.g. multipl...
3,6:102(1).a,6:102,1,post_condition,"If two or more persons are liable to compensate the same damage, t...",Rust op ieder van twee of meer personen een verplichting tot vergo...,[liable persons],[],[],[],[],[article 10],[without prejudice to their internal contribution obligations unde...,"[damage, joint and several liability, compensation, contribution]","Dutch Civil Code, Book 6, Title 6.1.10",Claude-draft,13/09/2026,Joint and several liability rule. Reference to art. 10 concerns in...
4,6:102(2).a,6:102,2,post_condition,For the determination of what these persons must contribute among ...,Voor de bepaling van hetgeen zij krachtens artikel 101 jegens elka...,[liable persons],[],[],[],[],[article 101],[],"[damage, division, contribution, proportion, equity]","Dutch Civil Code, Book 6, Title 6.1.10",Claude-draft,13/09/2026,Internal division of joint liability by reference to 6:101 (contri...

## 2. Corpus overview

Per-article summary followed by tag frequencies for each schema field.

Lists all articles and their attributes (number of : atoms, post-conditions, pre-conditions, legal relations, acts, geographical domain, temporal, explicit references, hierarchies, residual).

In [2]:
summary_stats(df)

   article_id  n_atoms  n_pre  n_post  actors  legal_relations  acts  geographical_domain  temporal  explicit_references  hierarchies  residual
0       6:101        3      1       2       3                0     1                    0         0                    1            0         3
1       6:102        2      0       2       2                0     0                    0         0                    2            1         2
2       6:106        4      0       4       4                0     0                    0         0                    1            0         4
3       6:107        2      0       2       2                0     2                    0         0                    0            0         2
4       6:108        2      0       2       2                0     2                    0         0                    0            0         2
5       6:162        4      1       3       2                0     1                    0         0                    0            1         4
6       6:163        1      0       1       1                0     0                    0         0                    0            0         1
7       6:165        1      0       1       1                0     0                    0         0                    1            0         1
8       6:170        3      2       1       3                2     0                    0         0                    0            0         3
9       6:173        2      1       1       2                0     0                    0         0                    0            0         2
10      6:174        2      0       2       2                0     0                    0         0                    0            0         2
11       6:74        3      1       2       3                1     1                    0         0                    1            0         3
12       6:75        1      0       1       1                0     0                    0         0                    0            0         1
13       6:76        1      0       1       1                1     1                    0         0                    0            0         1
14       6:77        1      0       1       1                1     1                    0         0                    0            0         1
15       6:78        1      0       1       1                1     1                    0         0                    0            0         1
16       6:81        1      0       1       1                1     0                    0         0                    1            0         1
17       6:82        2      0       2       2                2     2                    0         1                    0            0         2
18       6:83        3      0       3       3                3     0                    0         1                    1            0         3
19       6:95        1      0       1       0                0     0                    0         0                    0            0         1
20       6:96        5      1       4       0                0     0                    0         0                    1            0         5
21       6:97        1      0       1       1                0     1                    0         0                    0            0         1
22       6:98        1      0       1       1                0     0                    0         0                    0            0         1
23       6:99        1      0       1       1                0     1                    0         0                    0            0         1
24      7:446        5      1       4       4                2     1                    0         0                    1            0         5
25      7:448        8      2       6       8                4     8                    0         2                    1            0         8
26      7:453        2      0       2       2                1     2                    0         0                    0            0         2
27      7:454        8      2       6       7                2     6                    0         3                    1            1         8
28      7:455        3      2       1       2                1     1                    0         1                    1            2         3
29      7:457        6      2       4       5                3     5                    0         0                    3            1         6
30    synth:1        2      1       1       2                0     2                    2         1                    0            0         1
31   synth:10        3      2       1       2                0     3                    0         0                    0            1         3
32   synth:11        3      2       1       3                1     2                    0         1                    0            0         3
33   synth:12        2      1       1       1                0     2                    1         1                    0            0         2
34   synth:13        3      2       1       2                0     2                    1         1                    0            0         3
35   synth:14        2      1       1       1                0     2                    1         1                    0            0         2
36   synth:15        3      2       1       3                0     3                    0         0                    0            0         3
37    synth:2        2      1       1       1                0     1                    0         1                    0            0         2
38    synth:3        2      1       1       2                0     2                    1         1                    0            0         2
39    synth:4        2      1       1       1                0     1                    2         1                    0            0         2
40    synth:5        2      1       1       2                1     2                    0         0                    0            0         2
41    synth:6        3      2       1       2                0     2                    1         0                    0            1         2
42    synth:7        3      2       1       3                0     3                    0         1                    0            1         3
43    synth:8        3      2       1       3                0     3                    0         1                    0            1         3
44    synth:9        3      2       1       2                0     2                    0         0                    0            1         3

In [3]:
for field in LIST_FIELDS:
    freqs = tag_frequencies(df, field)
    if len(freqs) == 0:
        continue
    print(f'\n--- {field} ---')
    print(freqs.to_string())

--- actors ---
actors
patient                                   30
care provider                             21
debtor                                    14
injured party                              9
liable person                              5
someone other than patient                 5
colonist                                   5
creditor                                   4
third party                                3
liable persons                             3
deceased                                   3
wrongdoer                                  3
employer                                   3
subordinate                                3
possessor                                  3
citizen                                    3
party obliged to compensate                2
injured person                             2
client                                     2
unemancipated minor                        2
spouse                                     1
registered partner                         1
blood relative                             1
surviving relatives                        1
producer                                   1
public body                                1
auxiliary person                           1
court                                      1
physician                                  1
dentist                                    1
substitute                                 1
directly involved persons                  1
attending physician                        1
certified emergency medical technician     1
orbital health authority                   1
lead epidemiologist                        1
legal guardian                             1
colonial medical board                     1
automated triage system                    1
treating specialist                        1
chief geneticist                           1
Extraterrestrial Health Directorate        1
clone vat operator                         1
orbital stem-cell research division        1
designated primary caregiver               1
sector magistrate                          1
backup medical proxy                       1
chief cybersecurity officer                1
lunar health minister                      1
planetary governor                         1
chief xenobiologist                        1
port authority                             1
assigned quarantine officers               1
crew                                       1
bio-ethics committee                       1
lead neurosurgeon                          1

--- legal_relations ---
legal_relations
treatment agreement       13
obligation                10
service relationship       2
legal relationship         1
guardianship               1
caregiver relationship     1

--- acts ---
acts
compensates           8
provides              6
informs               4
obtains               2
withholds             2
observes              2
keeps record          2
requests              2
reduces               1
divides               1
commits               1
uses assistance       1
uses                  1
puts on notice        1
notifies              1
assesses              1
estimates             1
proves                1
binds                 1
gives                 1
consults              1
acts in accordance    1
sets up               1
includes              1
adds to               1
keeps                 1
destroys              1
ensures               1
breaches              1
resides               1
records               1
administers           1
purges                1
initiates             1
undergoes             1
admitted              1
transmits             1
dispatches            1
logged                1
proposed              1
exhibiting            1
discovered            1
reports               1
completed             1
incinerates           1
requisitions          1
suffers               1
executes              1
compromises           1
targets               1
severs                1
ingested              1
mandates              1
docks                 1
fails                 1
detains               1
possesses             1
substitutes           1

--- geographical_domain ---
geographical_domain
subterranean pressurized habitat zone    1
Lunar Medical Registry                   1
active servers                           1
hydroponic agricultural sector           1
sector-wide                              1
Level-5 bio-containment ward             1
affected sector                          1
geostationary medical satellite          1
docking perimeter                        1

--- temporal ---
temporal
upon request                                                                    2
permanently                                                                     2
immediate                                                                       2
reasonable period                                                               1
term for performance                                                            1
as soon as harm no longer feared                                                1
for twenty years                                                                1
from the time of last modification                                              1
longer than twenty years                                                        1
after request                                                                   1
during an extravehicular surface transit                                        1
within three lunar cycles                                                       1
previously                                                                      1
currently                                                                       1
until the patient achieves a legal state of certified radiological remission    1
upon approach                                                                   1

--- explicit_references ---
explicit_references
paragraph 1           5
paragraph 2           2
article 10            1
article 101           1
previous paragraph    1
article 162           1
second paragraph      1
article 82            1
article 83            1
article 74            1
article 455           1
article 448           1
article 454           1
article 450           1
article 465           1

--- hierarchies ---
hierarchies
without prejudice to their internal contribution obligations under article 10                        1
subject to the presence of a ground for justification                                                1
Without prejudice to the provisions of article 455                                                   1
Paragraph 1 does not apply insofar as                                                                1
nor insofar as                                                                                       1
Without prejudice to article 448 paragraph 3, second sentence                                        1
unless the pathogen is legally classified as a colony-threatening contagion                          1
except where the citizen has previously logged an authorized mechanical maintenance session          1
provided that the patient is not currently exhibiting symptoms of cryogenic stasis delirium          1
unless the anomaly is definitively categorized as a benign cosmic radiation artifact                 1
except where such material is explicitly requisitioned by the orbital stem-cell research division    1

--- residual ---
residual
damage                                            17
liability                                         13
attribution                                       10
performance                                        9
compensation                                       8
default                                            7
information                                        6
file                                               6
fault                                              5
failure to perform                                 5
property damage                                    5
equity                                             4
law                                                4
medical actions                                    4
data                                               4
contribution                                       3
non-property harm                                  3
unlawful act                                       3
reasonable costs                                   3
compensable                                        3
nature                                             3
treatment                                          3
documents                                          3
request                                            3
proportion                                         2
division                                           2
obligation                                         2
circumstances                                      2
ground                                             2
bodily injury                                      2
impairment                                         2
deceased                                           2
transfer                                           2
generally accepted views                           2
commerce                                           2
tortious act                                       2
task                                               2
conduct                                            2
harm                                               2
materialization                                    2
requirements                                       2
danger                                             2
permanently impossible                             2
prevention                                         2
health assessment                                  2
care                                               2
reasonably                                         2
examination                                        2
written                                            2
good care provider                                 2
necessary                                          2
consent                                            2
anomaly                                            2
circumstance                                       1
severity                                           1
mistakes                                           1
mutatis mutandis                                   1
joint and several liability                        1
intention                                          1
honour                                             1
good name                                          1
memory                                             1
spouse                                             1
registered partner                                 1
blood relative                                     1
seizure                                            1
agreement                                          1
court claim                                        1
mental injury                                      1
costs                                              1
third party                                        1
benefit                                            1
death                                              1
loss of maintenance                                1
surviving relatives                                1
funeral costs                                      1
reasonable                                         1
infringement                                       1
right                                              1
act                                                1
omission                                           1
legal duty                                         1
unwritten law                                      1
propriety                                          1
society                                            1
justification                                      1
norm                                               1
protective scope                                   1
Schutznorm                                         1
mental disability                                  1
physical disability                                1
age fourteen                                       1
chance                                             1
assignment                                         1
control                                            1
movable thing                                      1
special danger                                     1
defective product                                  1
product liability                                  1
circulation                                        1
structure                                          1
opstal                                             1
public road                                        1
state                                              1
application                                        1
legal act                                          1
thing                                              1
unsuitable                                         1
reasonableness                                     1
advantage                                          1
unjustified enrichment                             1
verzuim                                            1
due                                                1
written demand                                     1
notice                                             1
temporary inability                                1
written notification                               1
term                                               1
anticipated failure                                1
other harm                                         1
statutory obligation                               1
loss                                               1
profit                                             1
damage limitation                                  1
damage assessment                                  1
satisfaction                                       1
extrajudicial                                      1
legal costs                                        1
Code of Civil Procedure                            1
assessment                                         1
estimation                                         1
connection                                         1
event                                              1
alternative causation                              1
burden of proof                                    1
medical profession                                 1
medical business                                   1
procedures                                         1
curing                                             1
disease                                            1
obstetric assistance                               1
nursing                                            1
medical supervision                                1
insurance                                          1
training                                           1
employment                                         1
suitability                                        1
rights                                             1
obligations                                        1
health condition                                   1
developments                                       1
age of twelve years                                1
level of understanding                             1
reasonable knowledge                               1
purpose                                            1
consequences                                       1
risks                                              1
alternative methods                                1
health prospects                                   1
serious harm                                       1
therapeutic privilege                              1
interest                                           1
authority                                          1
withholding                                        1
another care provider                              1
work                                               1
responsibility                                     1
professional standard                              1
health                                             1
interventions                                      1
proper care                                        1
statement                                          1
duty                                               1
electronic                                         1
retention                                          1
substantial interest                               1
reasonably likely                                  1
provision                                          1
destruction                                        1
based on or by virtue of                           1
inspection                                         1
copies                                             1
confidentiality                                    1
personal privacy                                   1
limitations                                        1
substitute                                         1
activities                                         1
confidentiality duty                               1
ambient oxygen saturation baseline                 1
medical emergency                                  1
occurs                                             1
autonomous life-support protocols                  1
prior written consent                              1
deletion                                           1
gravitational adaptation biometrics                1
formally                                           1
specified data                                     1
pathogenic mutation                                1
detected                                           1
biological quarantine sequence                     1
artificial gravity acclimation therapy             1
physiological telemetry                            1
secured encrypted transmission link                1
identity                                           1
public health broadcasts                           1
pathogen                                           1
colony-threatening contagion                       1
legally classified                                 1
neural implant                                     1
erratic                                            1
hostile                                            1
bio-signatures                                     1
emergency retrieval drone                          1
authorized mechanical maintenance session          1
experimental radiation shield therapy              1
triple-verified digital consent                    1
symptoms                                           1
cryogenic stasis delirium                          1
structural anomaly                                 1
embryonic genetic profile                          1
definitively categorized                           1
benign cosmic radiation artifact                   1
synthetic organ cloning procedure                  1
surplus biological material                        1
material                                           1
explicitly                                         1
deep-space acute radiation syndrome                1
incapacitated                                      1
marrow-regeneration protocol                       1
jointly                                            1
medical data breach                                1
central psychiatric database                       1
malicious cyber-intrusion                          1
civilian life-support telemetry                    1
compromised network nodes                          1

## 3. Cross-article edges

One row per pair of atoms from different articles that share at least one tag
value in the same field. Each edge is one overlapping tag. Baseline strength
is the count of shared tags in that field.

Overview of 'Exact Match' edges, edges that are formed purely through a shared value within a field (field being actors, legal relations, residuals etc...)

In [4]:
edges = build_edge_table(df)
print(f'{len(edges)} cross-article edges')
print()
print('Edges by field:')
print(edges['field'].value_counts().to_string())
edges

1125 cross-article edges

Edges by field:
field
actors                 621
residual               347
legal_relations        108
acts                    35
explicit_references     11
temporal                 3

             atom_a         atom_b article_a article_b     field                              shared  strength  weighted_strength
0        6:101(1).a     6:102(1).a     6:101     6:102  residual              [contribution, damage]         2                2.0
1        6:101(1).a     6:102(2).a     6:101     6:102  residual  [contribution, damage, proportion]         3                3.0
2        6:101(1).a     6:106(1).a     6:101     6:106    actors                     [injured party]         1                1.0
3        6:101(1).a     6:106(1).b     6:101     6:106    actors                     [injured party]         1                1.0
4        6:101(1).a     6:106(1).c     6:101     6:106    actors                     [injured party]         1                1.0
...             ...            ...       ...       ...       ...                                 ...       ...                ...
1120  synth:11(1).a  synth:13(1).c  synth:11  synth:13    actors                           [patient]         1                1.0
1121  synth:11(1).b  synth:13(1).c  synth:11  synth:13    actors                           [patient]         1                1.0
1122  synth:11(1).c  synth:13(1).c  synth:11  synth:13    actors                           [patient]         1                1.0
1123  synth:13(1).a  synth:15(1).a  synth:13  synth:15    actors                          [colonist]         1                1.0
1124  synth:13(1).a  synth:15(1).b  synth:13  synth:15    actors                          [colonist]         1                1.0

[1125 rows x 8 columns]

### Atoms as hubs and isolates

For each atom, the number of edges it has and which schema fields produce
them. High `n_edges` = hub. Zero edges = the atom shares no tags with any
other article's atoms.

In [5]:
df_e = add_edge_summary(df, edges)
df_e.sort_values('n_edges', ascending=False)[
    ['atom_id', 'n_edges', 'connected_atoms', 'edge_fields']
]

           atom_id  n_edges                                                        connected_atoms                                edge_fields
32       6:78(1).a       52  [6:101(1).a, 6:101(2).a, 6:102(1).a, 6:102(2).a, 6:107(1).a, 6:107...  [actors, acts, legal_relations, residual]
26       6:74(1).a       52  [6:101(1).a, 6:101(2).a, 6:102(1).a, 6:102(2).a, 6:107(1).a, 6:107...  [actors, acts, legal_relations, residual]
71      7:455(1).a       52  [7:446(1).a, 7:446(3).a, 7:446(5).a, 7:448(1).a, 7:448(1).b, 7:448...        [actors, legal_relations, residual]
77      7:457(2).a       51  [6:74(1).a, 6:74(2).a, 6:76(1).a, 6:81(1).a, 6:82(1).a, 6:83(1).a,...  [actors, acts, legal_relations, residual]
74      7:457(1).a       48  [7:446(1).a, 7:446(3).a, 7:446(5).a, 7:448(1).a, 7:448(1).b, 7:448...  [actors, acts, legal_relations, residual]
..             ...      ...                                                                    ...                                        ...
104  synth:10(1).c        0                                                                     []                                         []
113  synth:14(1).a        0                                                                     []                                         []
111  synth:13(1).b        0                                                                     []                                         []
114  synth:14(1).b        0                                                                     []                                         []
117  synth:15(1).c        0                                                                     []                                         []

[118 rows x 4 columns]

In [6]:
df_e.loc[df_e['n_edges'] == 0, ['atom_id', 'condition_type', 'text']]

           atom_id  condition_type                                                                   text
14      6:162(2).a  post_condition  An unlawful act is deemed to be an infringement of a right and an ...
50      7:446(2).b  post_condition  Actions in the field of medicine also include other actions direct...
82    synth:2(1).a   pre_condition  If a medical emergency occurs during an extravehicular surface tra...
83    synth:2(1).b  post_condition  any certified emergency medical technician may administer autonomo...
85    synth:3(1).b  post_condition  the orbital health authority must purge the specified data from al...
86    synth:4(1).a   pre_condition  If a pathogenic mutation is detected within a hydroponic agricultu...
88    synth:5(1).a   pre_condition  If an unemancipated minor undergoes artificial gravity acclimation...
92    synth:6(1).c   pre_condition  unless the pathogen is legally classified as a colony-threatening ...
94    synth:7(1).b  post_condition  the automated triage system must dispatch an emergency retrieval d...
100   synth:9(1).b  post_condition  the chief geneticist must report the anomaly to the Extraterrestri...
101   synth:9(1).c   pre_condition  unless the anomaly is definitively categorized as a benign cosmic ...
102  synth:10(1).a   pre_condition                    If a synthetic organ cloning procedure is completed
103  synth:10(1).b  post_condition  the clone vat operator must incinerate any surplus biological mate...
104  synth:10(1).c   pre_condition  except where such material is explicitly requisitioned by the orbi...
108  synth:12(1).a   pre_condition  If a medical data breach compromises the colony's central psychiat...
111  synth:13(1).b   pre_condition  and the resulting physiological symptoms cannot be cross-reference...
113  synth:14(1).a   pre_condition  If a commercial transport vessel docks with an active medical emer...
114  synth:14(1).b  post_condition  the port authority and the assigned quarantine officers must physi...
117  synth:15(1).c  post_condition  the bio-ethics committee and the lead neurosurgeon must substitute...

## 4. Article-level connectivity

Aggregate atom-level edges up to article pairs. Useful for a first look at
which articles cluster together at the coarse level.

Overview of total edges across different *articles* and their shared fields.

In [7]:
article_connectivity(edges)

    article_a article_b  n_edges              fields
0       6:101     6:102        5          [residual]
1       6:101     6:106       14  [actors, residual]
2       6:101     6:107        5  [actors, residual]
3       6:101     6:108        3          [residual]
4       6:101     6:162        7  [actors, residual]
..        ...       ...      ...                 ...
262   synth:8  synth:13        3            [actors]
263   synth:8  synth:15        2            [actors]
264   synth:8   synth:9        1            [actors]
265   synth:9  synth:13        1            [actors]
266   synth:9  synth:15        2            [actors]

[267 rows x 4 columns]

## 5. Tag weighting

Common tags (`patient`, `care provider`) appear in most atoms and carry
little discriminative signal. IDF down-weights them and up-weights rare
tags. Two modes: `idf` (default, log inverse document frequency) and `tf`
(raw frequency).

Lists bottom 8 tags ( words or phrases that are very common they appear frequently across corpus so does not help in inferring knowledge).

Second output lists edges with the highest weights ie edges formed across tags that are lesser common accross the corpus.

In [8]:
weights_idf = compute_tag_weights(df, method='idf')
print(f'Computed {len(weights_idf)} tag weights')
print()
print('Top 8 (most discriminative):')
print(show_tag_weights(weights_idf).head(8).to_string())
print()
print('Bottom 8 (least discriminative):')
print(show_tag_weights(weights_idf).tail(8).to_string())

Computed 428 tag weights

Top 8 (most discriminative):
      field                                       tag  weight
0  residual      internal biological integration risk   4.086
1  residual            guaranteed mechanical mobility   4.086
2  residual              customized external bio-suit   4.086
3  residual                                 procedure   4.086
4  residual                documented medical history   4.086
5  residual  severe neuro-synthetic implant rejection   4.086
6    actors                                    spouse   4.086
7  residual                                 mandatory   4.086

Bottom 8 (least discriminative):
               field                  tag  weight
420  legal_relations           obligation  2.3812
421         residual          attribution  2.3812
422  legal_relations  treatment agreement  2.1401
423         residual            liability  2.1401
424           actors               debtor  2.0711
425         residual               damage  1.8888
426           actors        care provider  1.6881
427           actors              patient  1.3451

In [9]:
edges_weighted = build_edge_table(df, weights=weights_idf)

print('Top 5 by uniform strength (count of shared tags):')
print(edges_weighted.sort_values('strength', ascending=False).head(5)[
    ['atom_a', 'atom_b', 'shared', 'strength']
].to_string(index=False))
print()
print('Top 5 by IDF-weighted strength:')
print(edges_weighted.sort_values('weighted_strength', ascending=False).head(5)[
    ['atom_a', 'atom_b', 'shared', 'weighted_strength']
].to_string(index=False))

Top 5 by uniform strength (count of shared tags):
    atom_a     atom_b                                                        shared  strength
6:162(3).a  6:75(1).a [attribution, commerce, fault, generally accepted views, law]         5
 6:74(2).a  6:81(1).a                [default, performance, permanently impossible]         3
7:448(3).b 7:457(1).a          [care provider, patient, someone other than patient]         3
6:173(1).a 6:174(1).a                    [liability, materialization, requirements]         3
6:101(1).a 6:102(2).a                            [contribution, damage, proportion]         3

Top 5 by IDF-weighted strength:
    atom_a     atom_b                                                        shared  weighted_strength
6:162(3).a  6:75(1).a [attribution, commerce, fault, generally accepted views, law]            15.8993
6:173(1).a 6:174(1).a                    [liability, materialization, requirements]             9.5011
6:101(1).a 6:102(2).a                            [contribution, damage, proportion]             8.9621
 6:74(2).a  6:81(1).a                [default, performance, permanently impossible]             8.8567
6:101(1).b 6:102(2).a                                            [division, equity]             6.8502

## 6. Semantic similarity

Exact set intersection misses synonyms and related concepts. The semantic
layer computes cosine similarity between every pair of unique tag values in
each field, using a sentence-transformer. Pairs above the threshold become
implicit tag equivalences, which then promote to atom-level edges.

Expanding on exact matches by adding semantic similarity to form edges across field values that are also similar enough to form an edge, 'enough' determined by threshold currently set to 0.55.
Still Unsure what model works best LegalBert did not preform as well as I expected so switched back to mpnet for now.

Lists similarity pairs and number of semantic edges

In [10]:
from sentence_transformers import SentenceTransformer

model = SentenceTransformer('sentence-transformers/all-mpnet-base-v2') #not sure which to use still
sim_pairs = compute_tag_similarities(df, threshold=0.55, model=model)
sem_edges = build_semantic_edge_table(df, sim_pairs)

print(f'{len(sim_pairs)} high-similarity tag pairs')
print(f'{len(sem_edges)} semantic edges across atoms')
sim_pairs.head(10)

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

238 high-similarity tag pairs
839 semantic edges across atoms

                 field          tag_a           tag_b  similarity
0  explicit_references    article 454     article 455      0.9806
1  explicit_references    paragraph 1     paragraph 2      0.9579
2               actors  liable person  liable persons      0.9494
3  explicit_references     article 82      article 83      0.9321
4             residual      procedure      procedures      0.9258
5  explicit_references    article 448     article 454      0.9088
6  explicit_references    article 455     article 465      0.9082
7  explicit_references    article 454     article 465      0.9042
8             residual     obligation     obligations      0.8974
9               actors       creditor          debtor      0.8954

### Exact vs semantic coverage

Both channels operate on the same atoms. Exact edges are deterministic and
auditable; semantic edges catch synonyms exact matching misses.

Summary/Comparison of Semantic and Exact Edges.

In [11]:
# Combine both channels in one table
exact = edges.copy()
exact['edge_kind'] = 'exact'

sem = sem_edges.copy()
sem['edge_kind'] = 'semantic'
sem['shared'] = sem['matched_pairs']
sem['strength'] = sem['n_matches']
sem['weighted_strength'] = sem['max_similarity']

cols = ['edge_kind', 'atom_a', 'atom_b', 'field', 'shared', 'strength', 'weighted_strength']
combined = pd.concat([exact[cols], sem[cols]], ignore_index=True)

# Coverage overlap
exact_pairs = {(r.atom_a, r.atom_b) for _, r in exact.iterrows()}
sem_pairs_set = {(r.atom_a, r.atom_b) for _, r in sem.iterrows()}
sem_only = sem_pairs_set - exact_pairs
exact_only = exact_pairs - sem_pairs_set
both = sem_pairs_set & exact_pairs

print(f'Exact edges:                {len(exact)}')
print(f'Semantic edges:             {len(sem_edges)}')
print(f'Atom pairs, exact only:     {len(exact_only)}')
print(f'Atom pairs, semantic only:  {len(sem_only)}')
print(f'Atom pairs in both:         {len(both)}')

if sem_only:
    print()
    print('Atom pairs connected ONLY semantically (no exact tag overlap):')
    for a, b in sorted(sem_only):
        print(f'  {a} <-> {b}')

Exact edges:                1125
Semantic edges:             839
Atom pairs, exact only:     568
Atom pairs, semantic only:  454
Atom pairs in both:         326

Atom pairs connected ONLY semantically (no exact tag overlap):
  6:101(1).a <-> 6:108(2).a
  6:101(1).a <-> 6:173(1).a
  6:101(1).a <-> 6:96(1).a
  6:101(1).a <-> 6:96(2).a
  6:101(1).a <-> 6:96(2).b
  6:101(1).a <-> 6:96(2).c
  6:101(1).a <-> 7:448(3).a
  6:101(1).a <-> 7:455(1).a
  6:101(1).a <-> 7:455(2).b
  6:101(1).a <-> 7:457(1).b
  6:101(1).b <-> 6:102(1).a
  6:101(1).b <-> 6:107(1).a
  6:101(1).b <-> 6:107(1).b
  6:101(1).b <-> 6:108(1).a
  6:101(1).b <-> 6:162(2).a
  6:101(1).b <-> 6:95(1).a
  6:101(1).b <-> 6:99(1).a
  6:101(1).b <-> 7:446(5).a
  6:101(1).b <-> 7:448(3).b
  6:101(1).b <-> 7:453(1).b
  6:101(1).b <-> 7:454(3).b
  6:101(1).b <-> synth:12(1).b
  6:101(2).a <-> 6:173(2).a
  6:101(2).a <-> 6:96(1).a
  6:101(2).a <-> 6:96(2).c
  6:101(2).a <-> 6:96(3).a
  6:101(2).a <-> 7:446(5).a
  6:101(2).a <-> 7:448(3).a
  6:101(2).a <-> 7:453(1).b
  6:101(2).a <-> 7:455(2).b
  6:101(2).a <-> 7:457(1).b
  6:101(2).a <-> 7:457(3).b
  6:102(1).a <-> 6:108(2).a
  6:102(1).a <-> 6:165(1).a
  6:102(1).a <-> 6:173(1).a
  6:102(1).a <-> 6:174(1).a
  6:102(1).a <-> 6:174(2).a
  6:102(1).a <-> 6:76(1).a
  6:102(1).a <-> 6:81(1).a
  6:102(1).a <-> 6:82(2).a
  6:102(1).a <-> 6:96(1).a
  6:102(1).a <-> 6:96(2).a
  6:102(1).a <-> 6:96(2).b
  6:102(1).a <-> 6:96(2).c
  6:102(1).a <-> 7:448(3).a
  6:102(1).a <-> 7:454(3).a
  6:102(1).a <-> 7:455(2).b
  6:102(1).a <-> 7:457(1).a
  6:102(1).a <-> 7:457(1).b
  6:102(1).a <-> 7:457(3).a
  6:102(2).a <-> 6:108(2).a
  6:102(2).a <-> 6:165(1).a
  6:102(2).a <-> 6:173(1).a
  6:102(2).a <-> 6:81(1).a
  6:102(2).a <-> 6:96(1).a
  6:102(2).a <-> 6:96(2).a
  6:102(2).a <-> 6:96(2).b
  6:102(2).a <-> 6:96(2).c
  6:102(2).a <-> 7:448(3).a
  6:102(2).a <-> 7:448(3).b
  6:102(2).a <-> 7:454(3).a
  6:102(2).a <-> 7:455(2).b
  6:102(2).a <-> 7:457(1).a
  6:102(2).a <-> 7:457(1).b
  6:102(2).a <-> 7:457(3).a
  6:106(1).a <-> 6:173(1).a
  6:106(1).a <-> 6:96(1).a
  6:106(1).a <-> 6:96(2).a
  6:106(1).a <-> 6:96(2).b
  6:106(1).a <-> 6:96(2).c
  6:106(1).a <-> 6:99(1).a
  6:106(1).a <-> 7:448(2).a
  6:106(1).a <-> 7:448(3).a
  6:106(1).a <-> 7:448(3).b
  6:106(1).a <-> 7:457(1).b
  6:106(1).b <-> 6:107(1).b
  6:106(1).b <-> 6:108(1).a
  6:106(1).b <-> 6:165(1).a
  6:106(1).b <-> 6:170(1).a
  6:106(1).b <-> 6:170(1).c
  6:106(1).b <-> 6:173(1).a
  6:106(1).b <-> 6:74(1).a
  6:106(1).b <-> 6:76(1).a
  6:106(1).b <-> 6:78(1).a
  6:106(1).b <-> 6:82(2).a
  6:106(1).b <-> 6:96(1).a
  6:106(1).b <-> 6:96(2).a
  6:106(1).b <-> 6:96(2).b
  6:106(1).b <-> 6:96(2).c
  6:106(1).b <-> 6:97(1).a
  6:106(1).b <-> 6:99(1).a
  6:106(1).b <-> 7:448(3).a
  6:106(1).b <-> 7:448(3).b
  6:106(1).b <-> 7:454(3).b
  6:106(1).b <-> 7:457(1).b
  6:106(1).c <-> 6:107(1).a
  6:106(1).c <-> 6:107(1).b
  6:106(1).c <-> 6:165(1).a
  6:106(1).c <-> 6:173(1).a
  6:106(1).c <-> 6:82(2).a
  6:106(1).c <-> 6:96(1).a
  6:106(1).c <-> 6:96(2).a
  6:106(1).c <-> 6:96(2).b
  6:106(1).c <-> 6:96(2).c
  6:106(1).c <-> 7:448(3).a
  6:106(1).c <-> 7:457(1).b
  6:106(2).a <-> 6:107(1).a
  6:106(2).a <-> 6:107(1).b
  6:106(2).a <-> 6:74(2).a
  6:106(2).a <-> 6:96(3).a
  6:106(2).a <-> 7:446(3).a
  6:106(2).a <-> 7:448(2).a
  6:106(2).a <-> 7:455(2).a
  6:106(2).a <-> 7:457(3).b
  6:107(1).a <-> 6:165(1).a
  6:107(1).a <-> 6:173(2).a
  6:107(1).a <-> 6:96(1).a
  6:107(1).a <-> 6:96(2).c
  6:107(1).a <-> 7:446(5).a
  6:107(1).a <-> 7:448(3).a
  6:107(1).a <-> 7:453(1).b
  6:107(1).a <-> 7:455(2).b
  6:107(1).a <-> 7:457(1).b
  6:107(1).b <-> 6:173(1).a
  6:107(1).b <-> 6:96(1).a
  6:107(1).b <-> 6:96(2).a
  6:107(1).b <-> 6:96(2).b
  6:107(1).b <-> 6:96(2).c
  6:107(1).b <-> 6:96(3).a
  6:107(1).b <-> 7:448(3).a
  6:107(1).b <-> 7:455(2).b
  6:107(1).b <-> 7:457(1).b
  6:108(1).a <-> 6:173(2).a
  6:108(1).a <-> 6:96(1).a
  6:108(1).a <-> 6:96(2).c
  6:108(1).a <-> 7:446(5).a
  6:108(1).a <-> 7:448(3).a
  6:108(1).a <-> 7:453(1).b
  6:108(1).a <-> 7:455(2).b
  6:108(1).a <-> 7:457(1).b
  6:108(2).a <-> 6:77(1).a
  6:108(2).a <-> 6:96(2).a
  6:108(2).a <-> 6:96(2).b
  6:108(2).a <-> 6:96(2).c
  6:108(2).a <-> 7:446(3).a
  6:108(2).a <-> 7:448(2).a
  6:108(2).a <-> 7:454(3).b
  6:162(1).a <-> 6:173(1).a
  6:162(1).a <-> 6:96(1).a
  6:162(1).a <-> 6:96(2).a
  6:162(1).a <-> 6:96(2).b
  6:162(1).a <-> 6:96(2).c
  6:162(1).a <-> 7:448(3).a
  6:162(1).a <-> 7:454(3).a
  6:162(1).a <-> 7:455(2).b
  6:162(1).a <-> 7:457(1).b
  6:162(2).a <-> 6:165(1).a
  6:162(2).a <-> 6:75(1).a
  6:162(2).a <-> 6:83(1).b
  6:162(2).a <-> 6:95(1).a
  6:162(2).a <-> 7:446(5).a
  6:162(2).a <-> 7:454(3).b
  6:162(2).a <-> 7:455(2).b
  6:162(2).a <-> 7:457(1).c
  6:162(3).a <-> 6:83(1).b
  6:162(3).a <-> 7:446(1).a
  6:163(1).a <-> 6:173(1).a
  6:163(1).a <-> 6:96(1).a
  6:163(1).a <-> 6:96(2).a
  6:163(1).a <-> 6:96(2).b
  6:163(1).a <-> 6:96(2).c
  6:163(1).a <-> 7:448(3).a
  6:163(1).a <-> 7:455(2).b
  6:163(1).a <-> 7:457(1).b
  6:165(1).a <-> 7:448(1).a
  6:165(1).a <-> 7:448(1).c
  6:165(1).a <-> 7:454(3).a
  6:165(1).a <-> 7:457(1).a
  6:165(1).a <-> 7:457(3).a
  6:170(1).a <-> 6:173(2).a
  6:170(1).a <-> 6:96(1).a
  6:170(1).a <-> 6:96(2).c
  6:170(1).a <-> 7:446(5).a
  6:170(1).a <-> 7:448(3).a
  6:170(1).a <-> 7:453(1).b
  6:170(1).a <-> 7:455(2).b
  6:170(1).a <-> 7:457(1).b
  6:173(1).a <-> 6:74(1).a
  6:173(1).a <-> 6:78(1).a
  6:173(1).a <-> 6:83(1).b
  6:173(1).a <-> 6:83(1).c
  6:173(1).a <-> 6:95(1).a
  6:173(1).a <-> 6:97(1).a
  6:173(1).a <-> 7:446(5).a
  6:173(1).a <-> 7:448(3).a
  6:173(1).a <-> 7:453(1).b
  6:173(1).a <-> synth:10(1).c
  6:173(1).a <-> synth:12(1).b
  6:173(2).a <-> 6:174(2).a
  6:173(2).a <-> 6:74(1).a
  6:173(2).a <-> 6:76(1).a
  6:173(2).a <-> 6:78(1).a
  6:173(2).a <-> 6:82(2).a
  6:173(2).a <-> 6:83(1).c
  6:173(2).a <-> 6:96(2).a
  6:173(2).a <-> 6:96(2).b
  6:173(2).a <-> 6:98(1).a
  6:173(2).a <-> 6:99(1).a
  6:174(1).a <-> 6:74(1).a
  6:174(1).a <-> 6:78(1).a
  6:174(1).a <-> 6:83(1).c
  6:174(1).a <-> 7:446(5).a
  6:174(1).a <-> 7:448(2).a
  6:174(1).a <-> 7:453(1).b
  6:174(1).a <-> 7:457(1).b
  6:174(1).a <-> synth:10(1).c
  6:174(1).a <-> synth:12(1).b
  6:174(2).a <-> 7:446(5).a
  6:174(2).a <-> 7:448(2).a
  6:174(2).a <-> 7:453(1).b
  6:174(2).a <-> 7:457(1).b
  6:74(1).a <-> 6:96(1).a
  6:74(1).a <-> 6:96(2).a
  6:74(1).a <-> 6:96(2).b
  6:74(1).a <-> 6:96(2).c
  6:74(1).a <-> 7:448(3).a
  6:74(1).a <-> 7:455(2).b
  6:74(1).a <-> 7:457(1).b
  6:74(2).a <-> 6:96(3).a
  6:74(2).a <-> 7:457(3).b
  6:75(1).a <-> 6:95(1).a
  6:75(1).a <-> 7:446(1).a
  6:76(1).a <-> 7:446(5).a
  6:76(1).a <-> 7:453(1).b
  6:77(1).a <-> 7:446(3).a
  6:77(1).a <-> 7:446(5).a
  6:77(1).a <-> 7:448(2).a
  6:77(1).a <-> 7:454(3).b
  6:78(1).a <-> 6:96(1).a
  6:78(1).a <-> 6:96(2).a
  6:78(1).a <-> 6:96(2).b
  6:78(1).a <-> 6:96(2).c
  6:78(1).a <-> 7:448(3).a
  6:78(1).a <-> 7:448(3).b
  6:78(1).a <-> 7:455(2).b
  6:78(1).a <-> 7:457(1).a
  6:78(1).a <-> 7:457(1).b
  6:78(1).a <-> 7:457(1).c
  6:78(1).a <-> 7:457(2).a
  6:78(1).a <-> 7:457(3).b
  6:78(1).a <-> synth:11(1).c
  6:78(1).a <-> synth:15(1).b
  6:81(1).a <-> 7:454(3).a
  6:81(1).a <-> 7:457(1).a
  6:82(2).a <-> 7:446(5).a
  6:82(2).a <-> 7:453(1).b
  6:83(1).b <-> 6:96(1).a
  6:83(1).b <-> 6:96(2).a
  6:83(1).b <-> 6:96(2).b
  6:83(1).b <-> 6:96(2).c
  6:83(1).b <-> 7:448(3).a
  6:83(1).b <-> 7:454(3).a
  6:83(1).b <-> 7:455(2).b
  6:83(1).b <-> 7:457(1).a
  6:83(1).b <-> 7:457(1).b
  6:83(1).b <-> 7:457(3).a
  6:95(1).a <-> 7:446(5).a
  6:95(1).a <-> 7:448(3).a
  6:95(1).a <-> 7:455(2).b
  6:95(1).a <-> 7:457(1).b
  6:95(1).a <-> 7:457(1).c
  6:95(1).a <-> synth:12(1).b
  6:96(1).a <-> 6:97(1).a
  6:96(1).a <-> 6:98(1).a
  6:96(1).a <-> 6:99(1).a
  6:96(2).a <-> 6:97(1).a
  6:96(2).a <-> 7:446(3).a
  6:96(2).a <-> 7:446(5).a
  6:96(2).a <-> 7:453(1).b
  6:96(2).a <-> 7:454(3).b
  6:96(2).a <-> 7:457(1).b
  6:96(2).b <-> 6:97(1).a
  6:96(2).b <-> 7:446(3).a
  6:96(2).b <-> 7:446(5).a
  6:96(2).b <-> 7:453(1).b
  6:96(2).b <-> 7:454(3).b
  6:96(2).c <-> 6:97(1).a
  6:96(2).c <-> 6:98(1).a
  6:96(2).c <-> 6:99(1).a
  6:96(2).c <-> 7:446(3).a
  6:96(2).c <-> 7:454(3).b
  6:96(3).a <-> 7:446(3).a
  6:96(3).a <-> 7:448(2).a
  6:96(3).a <-> 7:455(2).a
  6:97(1).a <-> 7:446(2).a
  6:97(1).a <-> 7:446(5).a
  6:97(1).a <-> 7:448(1).a
  6:97(1).a <-> 7:448(3).a
  6:97(1).a <-> 7:448(3).d
  6:97(1).a <-> 7:453(1).a
  6:97(1).a <-> 7:455(2).b
  6:97(1).a <-> 7:457(1).b
  6:97(1).a <-> synth:11(1).c
  6:97(1).a <-> synth:5(1).b
  6:98(1).a <-> 7:446(5).a
  6:98(1).a <-> 7:448(3).a
  6:98(1).a <-> 7:453(1).b
  6:98(1).a <-> 7:455(2).b
  6:98(1).a <-> 7:457(1).b
  6:99(1).a <-> 7:446(5).a
  6:99(1).a <-> 7:448(3).a
  6:99(1).a <-> 7:453(1).b
  6:99(1).a <-> 7:455(2).b
  6:99(1).a <-> 7:457(1).b
  7:446(1).a <-> 7:457(1).b
  7:446(1).a <-> synth:14(1).a
  7:446(1).a <-> synth:15(1).b
  7:446(1).a <-> synth:2(1).a
  7:446(2).a <-> 7:448(1).a
  7:446(2).a <-> 7:448(2).a
  7:446(2).a <-> 7:454(1).a
  7:446(2).a <-> 7:454(1).b
  7:446(2).a <-> synth:14(1).a
  7:446(2).a <-> synth:15(1).b
  7:446(2).a <-> synth:15(1).c
  7:446(2).a <-> synth:2(1).a
  7:446(2).a <-> synth:6(1).c
  7:446(2).b <-> 7:448(1).a
  7:446(2).b <-> 7:448(1).b
  7:446(2).b <-> 7:448(1).c
  7:446(2).b <-> 7:448(2).a
  7:446(2).b <-> 7:448(3).a
  7:446(2).b <-> 7:448(3).b
  7:446(2).b <-> 7:448(3).c
  7:446(2).b <-> 7:448(3).d
  7:446(2).b <-> 7:453(1).a
  7:446(2).b <-> 7:453(1).b
  7:446(2).b <-> 7:454(1).a
  7:446(2).b <-> 7:454(1).b
  7:446(2).b <-> 7:454(1).c
  7:446(2).b <-> 7:454(1).d
  7:446(2).b <-> 7:454(2).a
  7:446(2).b <-> 7:454(3).a
  7:446(2).b <-> 7:455(1).a
  7:446(2).b <-> 7:457(1).a
  7:446(2).b <-> 7:457(2).a
  7:446(2).b <-> 7:457(3).b
  7:446(2).b <-> synth:1(1).b
  7:446(2).b <-> synth:14(1).a
  7:446(2).b <-> synth:15(1).b
  7:446(2).b <-> synth:2(1).a
  7:446(2).b <-> synth:4(1).b
  7:446(2).b <-> synth:8(1).b
  7:446(3).a <-> 7:457(1).b
  7:446(3).a <-> 7:457(3).b
  7:446(3).a <-> synth:14(1).a
  7:446(3).a <-> synth:15(1).b
  7:446(3).a <-> synth:2(1).a
  7:446(5).a <-> 7:448(3).d
  7:446(5).a <-> 7:453(1).b
  7:446(5).a <-> 7:454(1).d
  7:446(5).a <-> 7:454(3).a
  7:446(5).a <-> 7:454(3).b
  7:446(5).a <-> 7:457(1).c
  7:446(5).a <-> 7:457(3).b
  7:448(1).a <-> 7:457(1).b
  7:448(1).a <-> 7:457(1).c
  7:448(1).a <-> synth:2(1).a
  7:448(1).a <-> synth:5(1).b
  7:448(1).b <-> 7:457(1).b
  7:448(1).b <-> 7:457(1).c
  7:448(1).b <-> synth:5(1).b
  7:448(1).c <-> 7:457(1).b
  7:448(1).c <-> 7:457(1).c
  7:448(1).c <-> synth:5(1).b
  7:448(2).a <-> 7:457(1).b
  7:448(2).a <-> 7:457(1).c
  7:448(2).a <-> synth:5(1).b
  7:448(3).a <-> 7:457(1).b
  7:448(3).b <-> synth:15(1).b
  7:448(3).c <-> 7:457(1).b
  7:448(3).d <-> 7:454(3).b
  7:448(3).d <-> 7:455(2).a
  7:448(3).d <-> 7:457(1).b
  7:448(3).d <-> synth:11(1).b
  7:453(1).a <-> 7:454(1).e
  7:453(1).a <-> 7:455(2).a
  7:453(1).a <-> 7:457(1).b
  7:453(1).a <-> synth:11(1).b
  7:453(1).b <-> 7:454(3).b
  7:453(1).b <-> 7:455(2).a
  7:453(1).b <-> 7:457(1).b
  7:453(1).b <-> 7:457(1).c
  7:453(1).b <-> synth:11(1).b
  7:454(1).a <-> 7:457(1).b
  7:454(1).b <-> 7:457(1).b
  7:454(1).b <-> synth:3(1).b
  7:454(1).c <-> 7:457(1).b
  7:454(1).d <-> 7:457(1).b
  7:454(1).d <-> synth:11(1).b
  7:454(1).d <-> synth:3(1).b
  7:454(1).e <-> 7:457(1).b
  7:454(1).e <-> synth:12(1).b
  7:454(2).a <-> 7:457(1).b
  7:454(3).a <-> 7:455(2).a
  7:454(3).a <-> 7:457(1).b
  7:454(3).a <-> 7:457(3).a
  7:454(3).a <-> synth:11(1).b
  7:454(3).a <-> synth:15(1).b
  7:454(3).b <-> 7:457(1).c
  7:455(1).a <-> 7:457(1).b
  7:455(1).a <-> synth:10(1).b
  7:455(1).a <-> synth:3(1).b
  7:455(2).a <-> 7:457(3).b
  7:455(2).a <-> synth:3(1).b
  7:457(1).a <-> synth:15(1).b
  7:457(1).a <-> synth:2(1).b
  7:457(1).b <-> synth:1(1).a
  7:457(1).b <-> synth:1(1).b
  7:457(1).b <-> synth:11(1).a
  7:457(1).b <-> synth:11(1).b
  7:457(1).b <-> synth:11(1).c
  7:457(1).b <-> synth:13(1).c
  7:457(1).b <-> synth:15(1).b
  7:457(1).b <-> synth:6(1).a
  7:457(1).b <-> synth:6(1).b
  7:457(1).b <-> synth:8(1).b
  7:457(1).b <-> synth:8(1).c
  7:457(1).c <-> synth:12(1).b
  7:457(1).c <-> synth:15(1).b
  7:457(1).c <-> synth:8(1).b
  7:457(2).a <-> synth:12(1).b
  7:457(2).a <-> synth:15(1).b
  7:457(3).a <-> synth:2(1).b
  7:457(3).b <-> synth:11(1).b
  7:457(3).b <-> synth:15(1).b
  7:457(3).b <-> synth:8(1).b
  synth:10(1).c <-> synth:15(1).a
  synth:13(1).c <-> synth:14(1).b
  synth:2(1).a <-> synth:14(1).a
  synth:2(1).b <-> synth:12(1).a
  synth:3(1).a <-> synth:10(1).c
  synth:3(1).b <-> synth:9(1).b
  synth:4(1).a <-> synth:6(1).c
  synth:4(1).b <-> synth:12(1).b
  synth:4(1).b <-> synth:15(1).c
  synth:5(1).b <-> synth:11(1).b
  synth:5(1).b <-> synth:12(1).a
  synth:6(1).c <-> synth:9(1).c
  synth:7(1).a <-> synth:15(1).b
  synth:8(1).b <-> synth:15(1).b
  synth:8(1).c <-> synth:13(1).b
  synth:9(1).b <-> synth:12(1).b
  synth:9(1).b <-> synth:13(1).c

## 7. Atom classifier

Given an atom-shaped input, score every corpus atom, then rank *articles* by
their best-matching atom. Every tag carries its IDF weight (rare tags count
more). Two channels:

- **exact_score** : weight of the tags shared exactly with the query
- **semantic_score** : for query tags not matched exactly, the most similar
  candidate tag (similarity x weight)

Both are normalised as a weighted cosine similarity (`normalize="cosine"`),
so they live on the same 0-1 scale and a candidate is not rewarded just for
having many tags. `combined_score` mixes them with `alpha` and is scaled so
that 1.0 means identical tags. `alpha=0.5` values an exact match and a
perfect semantic match equally. `normalize="none"` gives the original
unnormalised scores.

### 7.1 Classify an existing atom

Outputs Justification for classification.

In [12]:
query = df[df['atom_id'] == '7:454(2).a'].iloc[0].to_dict()
result = classify_atom(query, df, weights=weights_idf, sim_pairs=sim_pairs, alpha=0.5, top_k=5)
print(f"Predicted article: {result['predicted_article']}")
result['top_matches']

Predicted article: 7:455

      atom_id article_id  combined_score  exact_score  semantic_score
0  7:455(1).a      7:455          0.5281       0.4280          0.1001
1  7:448(1).b      7:448          0.4633       0.4633          0.0000
2  7:454(1).a      7:454          0.4219       0.4219          0.0000
3  7:454(1).b      7:454          0.2968       0.2968          0.0000
4  7:448(1).c      7:448          0.2640       0.2640          0.0000

### 7.2 Leave-one-out (LOO) evaluation, article level

Each atom in turn is the query: remove it, score the rest, rank the
*articles*, and record where its true article lands. Metrics:

- **hit@k** : share of queries whose true article is in the top k articles
- **mrr** : mean reciprocal rank (1 if first, 0.5 if second, 0.33 if third...)
- **random_*** : what a random article ranking would score on the same queries

IDF weights are recomputed inside every fold, so a held-out atom never
influences its own weights. Articles that have only one atom cannot be found
once that atom is held out; those queries count as misses and are flagged
`answerable=False`.

Evaluation uses the real statutory articles only. The synthetic Lunar
Medical Code is a pipeline fixture (see `tests/test_pipeline.py`).

In [13]:
df_eval = drop_synthetic(df)
weights_eval = compute_tag_weights(df_eval, method='idf')
print(f'Evaluating on {len(df_eval)} real atoms across {df_eval["article_id"].nunique()} articles')
print()

eval_df, summary = evaluate_article_retrieval(df_eval, sim_pairs=sim_pairs, alpha=0.5)
print('Overall:')
for k, v in summary.items():
    print(f'  {k:25s} {v}')
print()
eval_df[['atom_id', 'true_article', 'predicted_article', 'answerable', 'rank', 'rr']]

Evaluating on 80 real atoms across 30 articles

Overall:
  n_queries                 80
  n_answerable              69
  n_candidate_articles      29.9
  mrr                       0.6107
  hit@1                     0.4938
  hit@3                     0.7259
  hit@5                     0.7642
  hit@10                    0.8175
  mrr_answerable_only       0.708
  random_mrr                0.1149
  random_hit@1              0.0288
  random_hit@3              0.0862
  random_hit@5              0.1438
  random_hit@10             0.2875

       atom_id true_article predicted_article  answerable  rank        rr
0   6:101(1).a        6:101             6:102        True   2.0  0.500000
1   6:101(1).b        6:101             6:102        True   3.0  0.333333
2   6:101(2).a        6:101             6:170        True   9.0  0.111111
3   6:102(1).a        6:102             6:102        True   1.0  1.000000
4   6:102(2).a        6:102             6:102        True   1.0  1.000000
..         ...          ...               ...         ...   ...       ...
75  7:457(1).b        7:457             7:457        True   1.0  1.000000
76  7:457(1).c        7:457             6:162        True   2.0  0.500000
77  7:457(2).a        7:457             7:454        True   3.0  0.333333
78  7:457(3).a        7:457             7:457        True   1.0  1.000000
79  7:457(3).b        7:457             7:457        True   1.0  1.000000

[80 rows x 6 columns]

### 7.2b Scoring variants

The same evaluation with the original unnormalised scores, query-coverage
normalisation, and cosine normalisation (the default).

In [14]:
variants = {
    norm: evaluate_article_retrieval(df_eval, sim_pairs=sim_pairs, alpha=0.5, normalize=norm)[1]
    for norm in ['none', 'query', 'cosine']
}
pd.DataFrame(variants)

                         none    query   cosine
n_queries             80.0000  80.0000  80.0000
n_answerable          69.0000  69.0000  69.0000
n_candidate_articles  29.9000  29.9000  29.9000
mrr                    0.5926   0.5743   0.6107
hit@1                  0.4479   0.4521   0.4938
hit@3                  0.7134   0.6634   0.7259
hit@5                  0.7934   0.7476   0.7642
hit@10                 0.8300   0.8050   0.8175
mrr_answerable_only    0.6870   0.6659   0.7080
random_mrr             0.1149   0.1149   0.1149
random_hit@1           0.0288   0.0288   0.0288
random_hit@3           0.0862   0.0862   0.0862
random_hit@5           0.1438   0.1438   0.1438
random_hit@10          0.2875   0.2875   0.2875

### 7.3 Per-article breakdown

In [15]:
per_article = eval_df.groupby('true_article').agg(
    n_atoms=('atom_id', 'size'),
    answerable=('answerable', 'all'),
    hit_at_1=('hit@1', 'mean'),
    hit_at_3=('hit@3', 'mean'),
    mrr=('rr', 'mean'),
).round(3)
per_article

              n_atoms  answerable  hit_at_1  hit_at_3    mrr
true_article
6:101               3        True     0.000     0.667  0.315
6:102               2        True     1.000     1.000  1.000
6:106               4        True     0.750     0.750  0.792
6:107               2        True     1.000     1.000  1.000
6:108               2        True     1.000     1.000  1.000
6:162               4        True     0.500     0.767  0.651
6:163               1       False     0.000     0.000  0.000
6:165               1       False     0.000     0.000  0.000
6:170               3        True     1.000     1.000  1.000
6:173               2        True     0.250     1.000  0.542
6:174               2        True     0.500     1.000  0.750
6:74                3        True     0.333     0.333  0.450
6:75                1       False     0.000     0.000  0.000
6:76                1       False     0.000     0.000  0.000
6:77                1       False     0.000     0.000  0.000
6:78                1       False     0.000     0.000  0.000
6:81                1       False     0.000     0.000  0.000
6:82                2        True     0.000     0.000  0.200
6:83                3        True     0.667     1.000  0.833
6:95                1       False     0.000     0.000  0.000
6:96                5        True     0.600     0.800  0.712
6:97                1       False     0.000     0.000  0.000
6:98                1       False     0.000     0.000  0.000
6:99                1       False     0.000     0.000  0.000
7:446               5        True     0.800     1.000  0.867
7:448               8        True     0.875     1.000  0.938
7:453               2        True     0.000     0.000  0.103
7:454               8        True     0.375     1.000  0.625
7:455               3        True     0.000     0.667  0.292
7:457               6        True     0.667     1.000  0.806

### 7.4 Misclassifications

Atoms where the correct article didn't reach rank 1. Errors that look like
sibling articles are usually intuitive; errors that jump across topics are
worth digging into.

In [16]:
misses = eval_df[eval_df['hit@1'] < 1]
misses[['atom_id', 'true_article', 'predicted_article', 'answerable', 'rank']]

       atom_id true_article predicted_article  answerable  rank
0   6:101(1).a        6:101             6:102        True   2.0
1   6:101(1).b        6:101             6:102        True   3.0
2   6:101(2).a        6:101             6:170        True   9.0
8   6:106(2).a        6:106             6:101        True   6.0
15  6:162(2).b        6:162             6:101        True  16.0
16  6:162(3).a        6:162              6:75        True   2.0
17  6:163(1).a        6:163             6:106       False   NaN
18  6:165(1).a        6:165             6:162       False   NaN
22  6:173(1).a        6:173             6:174        True   3.0
23  6:173(2).a        6:173             6:173        True   1.5
24  6:174(1).a        6:174             6:173        True   2.0
27   6:74(1).b         6:74              6:75        True   4.0
28   6:74(2).a         6:74              6:81        True  10.0
29   6:75(1).a         6:75             6:162       False   NaN
30   6:76(1).a         6:76              6:83       False   NaN
31   6:77(1).a         6:77              6:74       False   NaN
32   6:78(1).a         6:78              6:74       False   NaN
33   6:81(1).a         6:81              6:83       False   NaN
34   6:82(1).a         6:82              6:83        True   5.0
35   6:82(2).a         6:82              6:83        True   5.0
37   6:83(1).b         6:83              6:81        True   2.0
39   6:95(1).a         6:95             6:106       False   NaN
40   6:96(1).a         6:96              6:95        True   2.0
44   6:96(3).a         6:96             7:446        True  19.5
45   6:97(1).a         6:97              6:98       False   NaN
46   6:98(1).a         6:98              6:74       False   NaN
47   6:99(1).a         6:99             6:107       False   NaN
49  7:446(2).a        7:446             7:448        True   3.0
54  7:448(1).b        7:448             7:455        True   2.0
61  7:453(1).a        7:453             7:448        True   7.0
62  7:453(1).b        7:453             7:457        True  16.0
63  7:454(1).a        7:454             7:448        True   2.0
67  7:454(1).e        7:454             7:457        True   2.0
68  7:454(2).a        7:454             7:455        True   3.0
69  7:454(3).a        7:454             6:102        True   3.0
70  7:454(3).b        7:454             7:446        True   3.0
71  7:455(1).a        7:455             7:448        True   3.0
72  7:455(2).a        7:455             7:448        True   2.0
73  7:455(2).b        7:455             7:457        True  23.5
76  7:457(1).c        7:457             6:162        True   2.0
77  7:457(2).a        7:457             7:454        True   3.0

### 7.5 Filter before semantic retrieval

A structural pre-filter before the classifier scores anything. The filter narrows the candidate set to atoms that share at least one tag with the query on the specified fields (default: `actors` and `acts`). The classifier then scores only the survivors.

At the current corpus size this is architecturally interesting rather than performance-critical — the classifier already isolates the right answers on 61 atoms without pre-filtering (as per 04/09/2026). The value shows at scale, and it makes the retrieval pipeline structurally.

In [17]:
from src.data.atom_table import filter_candidates

# Same LOO query as 7.2, run twice: once with the filter, once without
query = df[df['atom_id'] == '7:454(2).a'].iloc[0].to_dict()

result_no_filter = classify_atom(
    query, df.drop(df[df['atom_id'] == '7:454(2).a'].index),
    weights=weights_idf, sim_pairs=sim_pairs, alpha=0.5, top_k=5,
)

result_with_filter = classify_atom(
    query, df.drop(df[df['atom_id'] == '7:454(2).a'].index),
    weights=weights_idf, sim_pairs=sim_pairs, alpha=0.5, top_k=5,
    filter_fields=['actors', 'acts'],
)

print(f'Without filter: {len(result_no_filter["scores_by_atom"])} candidates scored')
print(f'With filter:    {len(result_with_filter["scores_by_atom"])} candidates scored')
print()
print('Top-5 without filter:')
print(result_no_filter['top_matches'].to_string(index=False))
print()
print('Top-5 with filter:')
print(result_with_filter['top_matches'].to_string(index=False))

Without filter: 117 candidates scored
With filter:    35 candidates scored

Top-5 without filter:
   atom_id article_id  combined_score  exact_score  semantic_score
7:455(1).a      7:455          0.5281       0.4280          0.1001
7:448(1).b      7:448          0.4633       0.4633          0.0000
7:454(1).a      7:454          0.4219       0.4219          0.0000
7:454(1).b      7:454          0.2968       0.2968          0.0000
7:448(1).c      7:448          0.2640       0.2640          0.0000

Top-5 with filter:
   atom_id article_id  combined_score  exact_score  semantic_score
7:455(1).a      7:455          0.5281       0.4280          0.1001
7:448(1).b      7:448          0.4633       0.4633          0.0000
7:454(1).a      7:454          0.4219       0.4219          0.0000
7:454(1).b      7:454          0.2968       0.2968          0.0000
7:448(1).c      7:448          0.2640       0.2640          0.0000

### 7.6 LOO comparison : filtered vs unfiltered

Full leave-one-out evaluation with and without the filter, at article level.

In [18]:
_, summary_no_filter = evaluate_article_retrieval(df_eval, sim_pairs=sim_pairs, alpha=0.5)
_, summary_filter = evaluate_article_retrieval(
    df_eval, sim_pairs=sim_pairs, alpha=0.5, filter_fields=['actors', 'acts'],
)
pd.DataFrame({'no filter': summary_no_filter, 'filter (actors + acts)': summary_filter})

C:\Users\gebruiker\Documents\Law & Tech\src\data\atom_table.py:562: UserWarning: Filter left no candidates; falling back on the full corpus.
  warnings.warn("Filter left no candidates; falling back on the full corpus.")
C:\Users\gebruiker\Documents\Law & Tech\src\data\atom_table.py:562: UserWarning: Filter left no candidates; falling back on the full corpus.
  warnings.warn("Filter left no candidates; falling back on the full corpus.")

C:\Users\gebruiker\Documents\Law & Tech\src\data\atom_table.py:562: UserWarning: Filter left no candidates; falling back on the full corpus.
  warnings.warn("Filter left no candidates; falling back on the full corpus.")

                      no filter  filter (actors + acts)
n_queries               80.0000                 80.0000
n_answerable            69.0000                 69.0000
n_candidate_articles    29.9000                 29.9000
mrr                      0.6107                  0.6399
hit@1                    0.4938                  0.5312
hit@3                    0.7259                  0.7384
hit@5                    0.7642                  0.7892
hit@10                   0.8175                  0.8175
mrr_answerable_only      0.7080                  0.7419
random_mrr               0.1149                  0.1149
random_hit@1             0.0288                  0.0288
random_hit@3             0.0862                  0.0862
random_hit@5             0.1438                  0.1438
random_hit@10            0.2875                  0.2875

## 8. Legal hierarchy

Every article belongs somewhere in the Dutch civil code tree:

    Rechtsgebied  (private_law / public_law)
        Wetboek       (BW, Sr, Sv, ...)
            Boek          (1-10 for BW)
                Titel         (e.g. 7.7 - Opdracht)
                    Afdeling      (e.g. 7.7.5 - WGBO)
                        Artikel       (e.g. 7:454)

`src/data/hierarchy.py` encodes this tree and parses article IDs into their
taxonomy path. Book 7 is fully populated because that is where the WGBO
corpus lives. Other books have names but no title-level breakdown yet.

### 8.1 Parse taxonomy for the corpus

Overview of every atom's taxonomy (Which article, book, titel and afdeling it belongs to).

In [19]:
from src.data.hierarchy import (
    parse_article_id, add_taxonomy_columns, tree_summary,
    build_hierarchy_edges, build_reference_edges, evaluate_at_levels,
)

df_tax = add_taxonomy_columns(df)
df_tax[['atom_id', 'article_id', 'boek', 'titel', 'afdeling', 'taxonomy_path']].head(12)

       atom_id article_id    boek titel afdeling                                                   taxonomy_path
0   6:101(1).a      6:101  Boek 6   6.1   6.1.10  private_law > BW > Boek 6 > Titel 6.1 > Afd 6.1.10 > Art 6:101
1   6:101(1).b      6:101  Boek 6   6.1   6.1.10  private_law > BW > Boek 6 > Titel 6.1 > Afd 6.1.10 > Art 6:101
2   6:101(2).a      6:101  Boek 6   6.1   6.1.10  private_law > BW > Boek 6 > Titel 6.1 > Afd 6.1.10 > Art 6:101
3   6:102(1).a      6:102  Boek 6   6.1   6.1.10  private_law > BW > Boek 6 > Titel 6.1 > Afd 6.1.10 > Art 6:102
4   6:102(2).a      6:102  Boek 6   6.1   6.1.10  private_law > BW > Boek 6 > Titel 6.1 > Afd 6.1.10 > Art 6:102
5   6:106(1).a      6:106  Boek 6   6.1   6.1.10  private_law > BW > Boek 6 > Titel 6.1 > Afd 6.1.10 > Art 6:106
6   6:106(1).b      6:106  Boek 6   6.1   6.1.10  private_law > BW > Boek 6 > Titel 6.1 > Afd 6.1.10 > Art 6:106
7   6:106(1).c      6:106  Boek 6   6.1   6.1.10  private_law > BW > Boek 6 > Titel 6.1 > Afd 6.1.10 > Art 6:106
8   6:106(2).a      6:106  Boek 6   6.1   6.1.10  private_law > BW > Boek 6 > Titel 6.1 > Afd 6.1.10 > Art 6:106
9   6:107(1).a      6:107  Boek 6   6.1   6.1.10  private_law > BW > Boek 6 > Titel 6.1 > Afd 6.1.10 > Art 6:107
10  6:107(1).b      6:107  Boek 6   6.1   6.1.10  private_law > BW > Boek 6 > Titel 6.1 > Afd 6.1.10 > Art 6:107
11  6:108(1).a      6:108  Boek 6   6.1   6.1.10  private_law > BW > Boek 6 > Titel 6.1 > Afd 6.1.10 > Art 6:108

### 8.2 Tree summary
How many atoms formed at every level of the structure

In [20]:
tree_summary(df_tax)

           level        value  n_atoms
0   rechtsgebied  private_law       80
1   rechtsgebied    synthetic       38
2        wetboek           BW       80
3        wetboek          LMC       38
4           boek       Boek 6       48
5           boek       (none)       38
6           boek       Boek 7       32
7          titel       (none)       38
8          titel          6.1       35
9          titel          7.7       32
10         titel          6.3       13
11      afdeling       (none)       38
12      afdeling        7.7.5       32
13      afdeling       6.1.10       22
14      afdeling        6.1.9       13
15      afdeling        6.3.2        7
16      afdeling        6.3.1        6

### 8.3 Containment edges

The hierarchy adds a new edge type  directed parent-child containment
edges from atoms up through the tree. These sit alongside the tag-overlap
and semantic edges from Sections 3 and 6.

So far all the edges are due to some similairty between atoms these new edges are different they mimic the structure of the Dutch Civil Code. They say "this thing is inside that thing." They're the edges of the tree structure itself.

In [21]:
hier_edges = build_hierarchy_edges(df_tax)
print(f'{len(hier_edges)} containment edges')
print()
print('Edges by level:')
print(hier_edges['level'].value_counts().to_string())

175 containment edges

Edges by level:
level
atom_to_article            118
article_to_afdeling         30
article_to_wetboek          15
afdeling_to_titel            5
titel_to_boek                3
boek_to_wetboek              2
wetboek_to_rechtsgebied      2

In [22]:
# Sample of the edges one row per unique containment relation
hier_edges.drop_duplicates(subset=['source', 'target'])

            source    target edge_kind                level
0       6:101(1).a     6:101  contains      atom_to_article
1            6:101    6.1.10  contains  article_to_afdeling
2           6.1.10       6.1  contains    afdeling_to_titel
3              6.1    Boek 6  contains        titel_to_boek
4           Boek 6        BW  contains      boek_to_wetboek
..             ...       ...       ...                  ...
170  synth:14(1).b  synth:14  contains      atom_to_article
171  synth:15(1).a  synth:15  contains      atom_to_article
172       synth:15       LMC  contains   article_to_wetboek
173  synth:15(1).b  synth:15  contains      atom_to_article
174  synth:15(1).c  synth:15  contains      atom_to_article

[175 rows x 4 columns]

### 8.4 Cross-article reference edges

A second structural edge type, orthogonal to containment: directed edges from
an atom to any article it explicitly references. Read from the
`explicit_references` field on each atom.

Example: `7:454(3).a` contains "Without prejudice to the provisions of article
455" that produces a directed edge `7:454(3).a → 7:455`. These edges are
asymmetric on purpose: `7:455` does not reference `7:454` back.

In [23]:
ref_edges, ref_unresolved = build_reference_edges(df_tax, return_unresolved=True)
print(f'{len(ref_edges)} reference edges built')
print(f'{len(ref_unresolved)} reference strings unresolved (worth inspecting)')
ref_edges

11 reference edges built
1 reference strings unresolved (worth inspecting)

        source target   edge_kind     ref_text
0   6:102(1).a   6:10  references   article 10
1   6:102(2).a  6:101  references  article 101
2   6:165(1).a  6:162  references  article 162
3    6:81(1).a   6:82  references   article 82
4    6:81(1).a   6:83  references   article 83
5    6:83(1).b   6:74  references   article 74
6   7:454(3).a  7:455  references  article 455
7   7:457(1).a  7:448  references  article 448
8   7:457(1).a  7:454  references  article 454
9   7:457(3).a  7:450  references  article 450
10  7:457(3).a  7:465  references  article 465

In [24]:
# Which articles are the busiest reference sources and targets?
if len(ref_edges):
    print('Sources (atoms that reference other articles):')
    print(ref_edges['source'].value_counts().to_string())
    print()
    print('Targets (articles being referenced):')
    print(ref_edges['target'].value_counts().to_string())
    print()
if len(ref_unresolved):
    print('Unresolved reference strings (need parser rules or annotation cleanup):')
    print(ref_unresolved.to_string(index=False))

Sources (atoms that reference other articles):
source
6:81(1).a     2
7:457(1).a    2
7:457(3).a    2
6:102(1).a    1
6:102(2).a    1
6:165(1).a    1
6:83(1).b     1
7:454(3).a    1

Targets (articles being referenced):
target
6:10     1
6:101    1
6:162    1
6:82     1
6:83     1
6:74     1
7:455    1
7:448    1
7:454    1
7:450    1
7:465    1

Unresolved reference strings (need parser rules or annotation cleanup):
   atom_id           ref_text          reason
6:106(2).a previous paragraph could not parse

### 8.5 Hierarchical accuracy

Leave-one-out with accuracy reported at each level of the tree, not just at
the article level. For a corpus concentrated in one afdeling (WGBO), the
book/titel/afdeling accuracies are trivially high because there is little
variation to distinguish. This becomes meaningful once atoms from other
sections (e.g. Book 6 obligations) are added.

In [25]:
eval_hier, summary_hier = evaluate_at_levels(
    df_tax, weights=weights_eval, sim_pairs=sim_pairs, alpha=0.5, top_k=3
)
print('Accuracy by level (higher = coarser prediction):')
for k, v in summary_hier.items():
    print(f'  {k:30s} {v}')

Accuracy by level (higher = coarser prediction):
  rechtsgebied_accuracy          1.0
  wetboek_accuracy               1.0
  boek_accuracy                  0.962
  titel_accuracy                 0.9
  afdeling_accuracy              0.888
  article_id_accuracy            0.5

In [26]:
# Per-atom breakdown: where did the prediction land in the tree?
eval_hier[['atom_id',
           'rechtsgebied_true', 'rechtsgebied_pred', 'rechtsgebied_hit',
           'boek_true',         'boek_pred',         'boek_hit',
           'article_id_true',   'article_id_pred',   'article_id_hit']]

       atom_id rechtsgebied_true rechtsgebied_pred  rechtsgebied_hit boek_true boek_pred  boek_hit article_id_true article_id_pred  article_id_hit
0   6:101(1).a       private_law       private_law              True    Boek 6    Boek 6      True           6:101           6:102           False
1   6:101(1).b       private_law       private_law              True    Boek 6    Boek 6      True           6:101           6:102           False
2   6:101(2).a       private_law       private_law              True    Boek 6    Boek 6      True           6:101           6:170           False
3   6:102(1).a       private_law       private_law              True    Boek 6    Boek 6      True           6:102           6:102            True
4   6:102(2).a       private_law       private_law              True    Boek 6    Boek 6      True           6:102           6:102            True
..         ...               ...               ...               ...       ...       ...       ...             ...             ...             ...
75  7:457(1).b       private_law       private_law              True    Boek 7    Boek 7      True           7:457           7:457            True
76  7:457(1).c       private_law       private_law              True    Boek 7    Boek 6     False           7:457           6:162           False
77  7:457(2).a       private_law       private_law              True    Boek 7    Boek 7      True           7:457           7:454           False
78  7:457(3).a       private_law       private_law              True    Boek 7    Boek 7      True           7:457           7:457            True
79  7:457(3).b       private_law       private_law              True    Boek 7    Boek 7      True           7:457           7:457            True

[80 rows x 10 columns]

## 9. Chained reasoning demo

The classifier answers "which atom is most similar to my query?" A query about
medical records finds 7:455, and stops there.

But real legal reasoning doesn't stop at one article. If a query lands on the
destruction duty (7:455), the reader also needs the retention override that
depends on it (7:454(3).a "Without prejudice to article 455..."). And often
the peripheral articles that share concepts.

This section walks the graph from the anchor match through three edge channels:

- **Reference edges** : explicit statutory citations (from `explicit_references`)
- **Shared-tag edges** : atoms overlapping on annotation tags (IDF-weighted)
- **Classifier ranking** : the anchor itself

Every step in the chain records *how* it was reached, so the result is
auditable.

### 9.1 Build the inputs

In [27]:
from src.data.reasoning import chained_reasoning, explain_chain

# Reference edges from section 8.4
if 'ref_edges' not in dir():
    ref_edges, _ = build_reference_edges(df_tax, return_unresolved=True)

# Weighted edges from section 5
if 'edges_weighted' not in dir():
    edges_weighted = build_edge_table(df, weights=weights_idf)

print(f'{len(df)} atoms, {len(edges_weighted)} tag edges, {len(ref_edges)} reference edges')

118 atoms, 1125 tag edges, 11 reference edges

### 9.2 Query 1 Destruction chain

A paraphrase of "can a patient request their file be destroyed?" Should anchor
on 7:455 and then follow the reference edge back to 7:454(3).a, the retention
override. If the graph is doing real work, both articles surface.

In [28]:
destruction_query = {
    'atom_id': 'Q_destruction',
    'article_id': 'UNKNOWN',
    'actors': ['patient', 'care provider'],
    'acts': ['destroys'],
    'residual': ['file', 'request'],
    'temporal': ['after request'],
    'legal_relations': [], 'explicit_references': [], 'hierarchies': [], 'geographical_domain': [],
}

result_destruction = chained_reasoning(
    destruction_query, df, ref_edges, edges_weighted,
    weights=weights_idf, sim_pairs=sim_pairs,
    alpha=0.5, top_k=2, max_hops=1,
    min_edge_strength=2.0, max_expansions_per_atom=3,
)
print(explain_chain(result_destruction))

Query: Q_destruction
  tags: actors=['patient', 'care provider'] · acts=['destroys'] · residual=['file', 'request']

Anchor matches (hop 0, classifier):
  7:455(1).a      via: classifier rank 1  [classifier, score=0.76]
                  → The care provider shall destroy the data from the file after a written or electronic request to that effect b…
  7:454(2).a      via: classifier rank 2  [classifier, score=0.61]
                  → The care provider shall, upon request, add to the file a statement issued by the patient

Hop 1 — graph expansion:
  7:457(1).a      via: 7:457(1).a references 7:454 ('article 454')  [reference_in]
                  → Without prejudice to article 448 paragraph 3, second sentence, the care provider ensures that no information…
  7:448(1).b      via: shares ['care provider', 'patient', 'treatment agreement', 'upon request'] with 7:454(2).a  [shared_tags, score=8.85]
                  → The care provider shall inform the patient in writing upon request
  7:446(1).a      via: shares ['care provider', 'patient', 'treatment agreement'] with 7:454(2).a  [shared_tags, score=5.17]
                  → The treatment agreement is the agreement whereby a care provider, in the exercise of a medical profession or…
  7:454(3).a      via: 7:454(3).a references 7:455 ('article 455')  [reference_in]
                  → Without prejudice to the provisions of article 455, the care provider shall keep the file for twenty years, c…
  7:454(1).b      via: shares ['care provider', 'patient', 'data', 'file'] with 7:455(1).a  [shared_tags, score=9.04]
                  → He keeps a record in the file of data concerning the health of the patient
  7:454(1).a      via: shares ['care provider', 'patient', 'treatment agreement', 'file'] with 7:455(1).a  [shared_tags, score=8.01]
                  → The care provider sets up a file relating to the treatment of the patient

Articles surfaced: 7:446, 7:448, 7:454, 7:455, 7:457

### 9.3 Query 2 Breach-of-duty chain

A paraphrase of "the care provider failed to keep proper records, causing harm
to the patient." Should cross-domain of WGBO's care-provider language and Book
6's obligation language share enough concepts that the chain surfaces both.

Notice there is no explicit reference edge between WGBO and Book 6 in the
current corpus. So this chain relies entirely on shared-tag edges . It is a test of whether the tag overlap is picking up real legal similarity.

In [29]:
breach_query = {
    'atom_id': 'Q_breach',
    'article_id': 'UNKNOWN',
    'actors': ['care provider', 'patient'],
    'acts': ['compensates'],
    'legal_relations': ['obligation'],
    'residual': ['damage', 'failure to perform', 'file'],
    'temporal': [], 'explicit_references': [], 'hierarchies': [], 'geographical_domain': [],
}

result_breach = chained_reasoning(
    breach_query, df, ref_edges, edges_weighted,
    weights=weights_idf, sim_pairs=sim_pairs,
    alpha=0.5, top_k=3, max_hops=1,
    min_edge_strength=2.0, max_expansions_per_atom=3,
)
print(explain_chain(result_breach))

Query: Q_breach
  tags: actors=['care provider', 'patient'] · acts=['compensates'] · legal_relations=['obligation'] · residual=['damage', 'failure to perform', 'file']

Anchor matches (hop 0, classifier):
  6:74(1).a       via: classifier rank 1  [classifier, score=0.59]
                  → Every failure to perform an obligation obliges the debtor to compensate the damage that the creditor suffers…
  6:78(1).a       via: classifier rank 2  [classifier, score=0.46]
                  → If a debtor obtains an advantage as a result of a failure to perform that cannot be attributed to him and tha…
  7:454(1).a      via: classifier rank 3  [classifier, score=0.38]
                  → The care provider sets up a file relating to the treatment of the patient

Hop 1 — graph expansion:
  6:77(1).a       via: shares ['debtor', 'obligation', 'attribution', 'failure to perform'] with 6:78(1).a  [shared_tags, score=9.82]
                  → If in performing an obligation the debtor uses a thing that is unsuitable, the resulting failure to perform i…
  6:82(2).a       via: shares ['creditor', 'debtor', 'obligation'] with 6:78(1).a  [shared_tags, score=7.62]
                  → If the debtor temporarily cannot perform, or if it becomes apparent from his statement that a written demand…
  6:83(1).c       via: shares ['creditor', 'debtor', 'obligation'] with 6:78(1).a  [shared_tags, score=7.62]
                  → The default occurs without notice when the creditor infers from a statement of the debtor that the debtor wil…
  7:457(1).a      via: 7:457(1).a references 7:454 ('article 454')  [reference_in]
                  → Without prejudice to article 448 paragraph 3, second sentence, the care provider ensures that no information…
  7:448(1).a      via: shares ['care provider', 'patient', 'treatment agreement', 'treatment'] with 7:454(1).a  [shared_tags, score=8.57]
                  → The care provider shall inform the patient clearly about the proposed examination, the proposed treatment, an…
  7:448(2).a      via: shares ['care provider', 'patient', 'treatment agreement', 'treatment'] with 7:454(1).a  [shared_tags, score=8.57]
                  → In performing the informing duty, the care provider shall be guided by what the patient should reasonably kno…
  6:83(1).b       via: 6:83(1).b references 6:74 ('article 74')  [reference_in]
                  → The default occurs without notice when the obligation arises from a tortious act or requires compensation of…
  6:83(1).a       via: shares ['debtor', 'obligation', 'performance'] with 6:74(1).a  [shared_tags, score=6.93]
                  → The default occurs without notice when a term set for performance passes without performance having taken pla…
  6:81(1).a       via: shares ['debtor', 'obligation', 'performance'] with 6:74(1).a  [shared_tags, score=6.93]
                  → The debtor is in default during the period that performance fails to occur after it has become due and the re…

Articles surfaced: 6:74, 6:77, 6:78, 6:81, 6:82, 6:83, 7:448, 7:454, 7:457

### 9.4 Query 3 Hospital Liability chain

A paraphrase of "the hospital is being sued for a doctor's mistake." Should
anchor on 6:170 (vicarious liability for subordinates) and expand to the
related tort and contract articles that share concepts like `damage`, `fault`,
`liability`.

In [30]:
hospital_query = {
    'atom_id': 'Q_hospital',
    'article_id': 'UNKNOWN',
    'actors': ['employer', 'subordinate', 'third party'],
    'residual': ['damage', 'fault', 'liability'],
    'legal_relations': ['service relationship'],
    'acts': [], 'temporal': [], 'explicit_references': [], 'hierarchies': [], 'geographical_domain': [],
}

result_hospital = chained_reasoning(
    hospital_query, df, ref_edges, edges_weighted,
    weights=weights_idf, sim_pairs=sim_pairs,
    alpha=0.5, top_k=2, max_hops=1,
    min_edge_strength=2.0, max_expansions_per_atom=3,
)
print(explain_chain(result_hospital))

Query: Q_hospital
  tags: actors=['employer', 'subordinate', 'third party'] · legal_relations=['service relationship'] · residual=['damage', 'fault', 'liability']

Anchor matches (hop 0, classifier):
  6:170(1).a      via: classifier rank 1  [classifier, score=0.92]
                  → For damage caused to a third party by a fault of a subordinate, the person in whose service the subordinate p…
  6:170(1).c      via: classifier rank 2  [classifier, score=0.59]
                  → and the person in whose service he was had, by virtue of their relevant legal relationship, control over the…

Hop 1 — graph expansion:
  6:76(1).a       via: shares ['conduct'] with 6:170(1).c  [shared_tags, score=3.68]
                  → If a debtor uses the assistance of other persons in performing an obligation, he is liable for their conduct…
  6:162(3).a      via: shares ['fault'] with 6:170(1).c  [shared_tags, score=2.99]
                  → An unlawful act can be attributed to the perpetrator if it is due to his fault or to a cause for which he is…
  6:75(1).a       via: shares ['fault'] with 6:170(1).c  [shared_tags, score=2.99]
                  → A failure to perform cannot be attributed to the debtor if it is neither due to his fault, nor for his accoun…
  6:101(2).a      via: shares ['third party', 'damage', 'liability'] with 6:170(1).a  [shared_tags, score=7.42]
                  → If for the damage there also exists a ground for liability of a third party, paragraph 1 applies mutatis muta…
  6:107(1).b      via: shares ['third party', 'damage'] with 6:170(1).a  [shared_tags, score=5.28]
                  → The liable person is also obliged to compensate the costs incurred by a third party for the benefit of the in…
  6:108(1).a      via: shares ['damage', 'liability'] with 6:170(1).a  [shared_tags, score=4.03]
                  → If a person dies as a result of an event for which another is liable to him, that other is obliged to compens…

Articles surfaced: 6:101, 6:107, 6:108, 6:162, 6:170, 6:75, 6:76

### 9.5 Structured result for the UI

`chained_reasoning()` returns a structured dict, not just text. This is what a
Streamlit UI would consume: `articles_touched` for a highlighted subgraph,
`chain` for the "explanation" panel, `primary_matches` for the ranked-answers
list.

In [31]:
print('Articles surfaced by the destruction query:')
print(' ', result_destruction['articles_touched'])
print()
print('Full chain (DataFrame view):')
import pandas as pd
pd.DataFrame(result_destruction['chain'])[
    ['hop', 'atom_id', 'article_id', 'edge_kind', 'via']
]

Articles surfaced by the destruction query:
  ['7:446', '7:448', '7:454', '7:455', '7:457']

Full chain (DataFrame view):

   hop     atom_id article_id     edge_kind                                                                    via
0    0  7:455(1).a      7:455    classifier                                                      classifier rank 1
1    0  7:454(2).a      7:454    classifier                                                      classifier rank 2
2    1  7:457(1).a      7:457  reference_in                            7:457(1).a references 7:454 ('article 454')
3    1  7:448(1).b      7:448   shared_tags  shares ['care provider', 'patient', 'treatment agreement', 'upon r...
4    1  7:446(1).a      7:446   shared_tags  shares ['care provider', 'patient', 'treatment agreement'] with 7:...
5    1  7:454(3).a      7:454  reference_in                            7:454(3).a references 7:455 ('article 455')
6    1  7:454(1).b      7:454   shared_tags    shares ['care provider', 'patient', 'data', 'file'] with 7:455(1).a
7    1  7:454(1).a      7:454   shared_tags  shares ['care provider', 'patient', 'treatment agreement', 'file']...

## 10. Natural-language queries

`src/data/query.py` turns a question in plain Dutch or English into query
atoms with Claude (same 9-label schema, reusing the corpus tag vocabulary),
then ranks articles for the whole question: each query atom scores the
articles, and the scores are summed, so an article that answers several
parts of the question rises to the top.

This calls the Anthropic API, which needs credentials and costs a few cents
per query. Set `RUN_LLM = True` to run it.

In [32]:
from src.data.query import retrieve_for_text

RUN_LLM = False

question = ('Het ziekenhuis heeft mijn medisch dossier kwijtgeraakt en nu kan ik '
            'niet bewijzen dat de behandeling verkeerd is gegaan.')

if RUN_LLM:
    result = retrieve_for_text(question, df_eval, weights=weights_eval, sim_pairs=sim_pairs)
    for atom in result['query_atoms']:
        tags = {f: atom[f] for f in LIST_FIELDS if atom[f]}
        print(f"{atom['atom_id']} [{atom['condition_type']}] {atom['text']}")
        print(f'    {tags}')
    display(result['article_ranking'].head(10))
else:
    print('Skipped: set RUN_LLM = True to call the API.')

Skipped: set RUN_LLM = True to call the API.